// Generates src/tokens/tokens.css and tokens.json from tokens/figma-variables.txt
// (a read-only export of the HOT Design System Figma variables).
import { readFileSync, writeFileSync } from 'node:fs'

const raw = readFileSync('tokens/figma-variables.txt', 'utf8').split('\n').filter(Boolean)

const cssName = (path) =>
  path
    .replace(/\(.*?\)/g, (m) => m.slice(1, -1)) // "(Hover)" -> "Hover"
    .split(/[\/\s_]+/)
    .filter(Boolean)
    .map((p, i) => (i === 0 ? p[0].toLowerCase() + p.slice(1) : p[0].toUpperCase() + p.slice(1)))
    .join('')

const collections = []
for (const line of raw) {
  if (line.startsWith('## ')) {
    const [, name, modes] = line.match(/^## (.+?) modes:(.+)$/)
    collections.push({ name, modes: modes.split('|'), vars: [] })
  } else {
    const [name, values] = line.split(' = ')
    collections.at(-1).vars.push({ name, values: values.split(' | ') })
  }
}

const [primitives, styleTokens, semantic] = collections
const hexOf = new Map(primitives.vars.map((v) => [v.name, v.values[0]]))
const resolve = (val) => (val.startsWith('->') ? hexOf.get(val.slice(2)) : val)

const seen = new Set()
const claim = (n) => {
  if (seen.has(n)) throw new Error(`Duplicate CSS variable name: ${n}`)
  seen.add(n)
}

let css = '/* GENERATED by scripts/generate-tokens.mjs from the HOT Design System Figma variables. Do not edit by hand. */\n:root {\n'
const json = { primitives: {}, styleTokens: {}, semantic: { modes: semantic.modes, tokens: [] } }

css += '  /* Primitives */\n'
for (const v of primitives.vars) {
  const n = cssName(v.name)
  claim(n)
  css += `  --${n}: ${v.values[0]};\n`
  const [family, step] = v.name.split('/')
  ;(json.primitives[family] ??= []).push({ step, name: `--${n}`, value: v.values[0] })
}

css += '\n  /* Style tokens (aliases of primitives) */\n'
for (const v of styleTokens.vars) {
  const n = cssName(v.name)
  claim(n)
  const val = v.values[0]
  css += val.startsWith('->') ? `  --${n}: var(--${cssName(val.slice(2))});\n` : `  --${n}: ${val};\n`
  const [family, group, ...rest] = v.name.split('/')
  const token = { label: rest.join('/'), name: `--${n}`, value: resolve(val), alias: val.startsWith('->') ? val.slice(2) : null }
  ;((json.styleTokens[family] ??= {})[group] ??= []).push(token)
}

css += '\n  /* Semantic tokens: default tone is Primary; switch with data-tone="error|warning|success" */\n'
const semRules = semantic.modes.map(() => '')
for (const v of semantic.vars) {
  const n = cssName(v.name)
  claim(n)
  semantic.modes.forEach((_, i) => {
    semRules[i] += `  --${n}: var(--${cssName(v.values[i].slice(2))});\n`
  })
  json.semantic.tokens.push({ name: `--${n}`, path: v.name, values: v.values.map((x) => ({ alias: x.slice(2), value: resolve(x) })) })
}
css += semRules[0] + '}\n'
semantic.modes.slice(1).forEach((m, i) => {
  css += `\n[data-tone="${m.toLowerCase()}"] {\n${semRules[i + 1]}}\n`
})

writeFileSync('src/tokens/tokens.css', css)
writeFileSync('src/tokens/tokens.json', JSON.stringify(json, null, 2) + '\n')
console.log(`Wrote ${seen.size} tokens`)
