// Generates src/icons/iconData.ts from tokens/icons-raw/all.json
// (a read-only export of the HOT Design System Figma icons: 14px, 16px and 24px artwork).
import { readFileSync, writeFileSync } from 'node:fs'

const raw = JSON.parse(readFileSync('tokens/icons-raw/all.json', 'utf8'))

// Figma name -> all lowercase, no separators ("WhatsApp" -> "whatsapp", "Email Templates" -> "emailtemplates").
const slugOf = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, '')

const camel = (a) => a.replace(/-([a-z])/g, (_, c) => c.toUpperCase())
const notes = []
const icons = {}

for (const [figmaName, svg] of Object.entries(raw)) {
  const [, sizeStr, iconName] = figmaName.match(/^Size=(\d+)px, Icon=(.*)$/)
  const size = Number(sizeStr)
  const slug = slugOf(iconName)
  if (icons[slug]?.[size]) {
    notes.push(`Duplicate ${slug} @${size}px ("${iconName}") ignored`)
    continue
  }

  // Unwrap a full-size clip group (it does not change the drawing) and drop <defs>.
  let body = svg.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '')
  body = body.replace(/<defs>[\s\S]*?<\/defs>/g, '')
  const clipRect = svg.match(/<clipPath[^>]*>\s*<rect ([^>]*)\/>/)
  if (clipRect && /x=|y=|transform=/.test(clipRect[1]) && !/x="0"/.test(clipRect[1])) {
    notes.push(`${slug} @${size}px has an offset clip rect; clip removed anyway`)
  }
  body = body.replace(/<g clip-path="[^"]*">/g, '').replace(/<\/g>/g, '')

  const els = []
  for (const m of body.matchAll(/<(path|rect|circle|ellipse|line)\s([^>]*?)\/>/g)) {
    const attrs = {}
    for (const a of m[2].matchAll(/([\w-]+)="([^"]*)"/g)) {
      let [, k, v] = a
      if ((k === 'stroke' || k === 'fill') && v !== 'none') v = 'currentColor'
      attrs[camel(k)] = v
    }
    els.push([m[1], attrs])
  }
  if (!els.length) notes.push(`${slug} @${size}px produced no shapes`)
  ;(icons[slug] ??= {})[size] = els
}

const names = Object.keys(icons).sort()
const out = `// GENERATED by scripts/generate-icons.mjs from the HOT Design System Figma icons. Do not edit by hand.
export type IconSize = 14 | 16 | 24
export type IconElement = [tag: 'path' | 'rect' | 'circle' | 'ellipse' | 'line', attrs: Record<string, string>]

export const iconNames = ${JSON.stringify(names)} as const
export type IconName = (typeof iconNames)[number]

export const iconData: Record<IconName, Partial<Record<IconSize, IconElement[]>>> = ${JSON.stringify(icons)}
`
writeFileSync('src/icons/iconData.ts', out)
console.log(`${names.length} icons written`)
console.log(notes.join('\n') || 'no notes')
